#!/usr/bin/env bash
# using scp to transfer file to server

path=$1
ip=$2
user=$3
ident=$4

if [ "$#" -lt 3 ];then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$ident" -o StrictHostKeyChecking=no "$path" "$user@$ip":~/
fi
