#!/usr/bin/env bash
# script configures the web server

sudo apt-get -y update
sudo apy-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "hello world" | sudo tee /var/www/html/index.html

# Restart nginx without using systemctl
nginx -s reload
