#!/usr/bin/env bash
# configures a server to install ngninx 

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null 2>&1

sudo nginx -s reload
