#!/usr/bin/env bash
# configures a server to install ngninx 

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

sudo nginx -s reload
