#!/usr/bin/env bash
# configures a server to install ngninx 

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
HOSTNAME=$(hostname)
replacement="add_header X-Served-By '$HOSTNAME';\n\tserver_name _;\n\t\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/google.com;\n\t\t}\n\t\terror_page 404 \/404.html;\n\t"
sudo sed -i s'/server_name _;/'"$replacement"'/' /etc/nginx/sites-available/default

sudo nginx -s reload

