#!/usr/bin/env bash
#using a while loop to echo Best school 10 times

VAR=1
while [ $VAR -le 20 ]
do
case $VAR in 
    4)
    echo 4
    echo  "bad luck from China"
    ;;
    9)
    echo 9
    echo "bad luck from Japan"
    ;;
    17)
    echo 17
    echo "bad luck from Italy"
    ;;
    *)
    echo "$VAR"
    ;;
esac
((VAR++))
done