#!/usr/bin/env bash
# allow deny all incoming traffic except on 22, 442, 80
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 442
sudo ufw route allow in 8080/tcp out on 80/tcp
sudo ufw enable
